name: ueek_tempo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  geocode: ^1.0.3
  geolocator: ^11.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  fonts: 
    - family: Sarabun
      fonts:
      - asset: fonts/Sarabun-Regular.ttf
        weight: 600
    - family: Mukta
      fonts:
      - asset: fonts/Mukta-Regular.ttf
